

services:
  web:
    build: .
    command: gunicorn monblog.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: monblog
      POSTGRES_USER: monbloguser
      POSTGRES_PASSWORD: monblogpass
    volumes:
      - postgres_data:/var/lib/postgresql/data/

volumes:
  postgres_data: